# Generated by Django 2.2.6 on 2019-11-05 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20191104_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmuser',
            name='user',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
